language: python
python:
    - 3.5
script:
    - echo building...
deploy:
    provider: pypi
    user: andykuszyk
    password:
        secure: KooyUf5URL4P4pIZHwJ2hMoGDy9DqqfuNgcRLZ55PAtMAQzrXNzxVWMvkTdPbJkqE+dJwreMHi6kMpEt1baaCe4pecDc9sjJTKiq8KpiK7VfgvS28Zj4f+OXuaWOclQdj7NiEbqDg7LxKqyp3R403j3FIlJ6nfeMTgwV+UF1qySQNSWcYqjm5ndjhEY+5iJkwvpehKx3YCKMMnN3xpDOeTpoeegSN/JLfM8hKayjk7cwSx/7Ivi6wawFfO4E7C6wnCgN+ct3gqIBVEN3obYbeuOGsUDMrPw4ltGz6ZTj89FI8htus0RKwsYpuFZMjE2CammkjWcb3BTFjR1JTLKxbbPYRQANPSFKx6SE8SFfXTELvhgVc6UV9jH3P5V65bnm7X6hRHbWndPOvbVy3rX+f2VT05bpIol+j1NH6g0XN6wQGdSQ5bsltZxXX/X7LoMVNcKHLlUpiL5G4gDWQUcVC1oiaJ32cRX/yI63/YQJs6cH+S1m+rJLjfgPBJqadavk1eIHF5ObAObWWk8gwCpjWgC6Sqm0mdqfMgAXBKl5MOL1HcM5Yjaop2qv5Zg06EaKYeH6VbyQwAgtR8aDn6FN1JnlMzQk/Z7CNiwDbnPWKZplodANn5TppqOaX6RjvAq+VKy29Ne741j9sGV7YbnHmVjfaMqJqguQVtwyYcEimDE=
    on:
#        tags: true

