language: python
python:
    - 3.5
script:
    - echo building...
deploy:
    provider: pypi
    user: "andykuszyk"
    password:
        secure: "hQkoqi0BQK1X21lyI2bAGCiC3NrK5nc88lnHSY5zuhaMF/ODwFUzegfjXzBrwhEOZ3zAQribxiMBIDcZIYSYTiWcxUNuKKUAzkwyNtXotO7lK66VbLsPsysQPx29o/uEbtHZyIxoauCvpWzACMND8GDCctp0MGBqxCiC9SRu6hbKBgSsG1SwhKz49SlL0v9AY1i/fxXjtk27/dM7Kd3cDodUUQCeM5IjwMkr4vHrxuTTD1Z8w6nxd8fAqMUfI0+5UWzsZ4Ld2omQcroKzykikYnYJQNAO1a0E75ne+p9Of3GzI4TRWIoAqPVYT+C78F7Z0RDoXyUHXLWzUvLtwMdesoMh8Mc3k+7R87knFvzhsiLqqK69GxwoXSh1kpa1Iq5yDEDqmOkhbA2cWufIidqAwAvSV9syaQcE/ZoeP6ajW/P9POlbK6ClqLjfhIoW0qj3RteNEmX4lRBugWZYXzq1V9E12UYz6abkYhU3l/u83AORKhsn2AdPYjE5w0LlAAwCZ4DWq1giZu3OPxH25xhBxdetnF9W6Wl0/8Cbyw0sAUvtT0TTHZokclkLFYOvEq62OxL5Wq0k2+bmfA59DjrcD6ejD1RlJMd9CKVfhvOuDEiKfiHfTMfU2MC8yEHnXiEAdD0lFEoBlSCBQMuKjIjMf8R4JF/7GPH893/JJyfn0w="
    on:
#        tags: true
